create table if not exists public.inscriptions (
  id bigint generated by default as identity primary key,
  numero text,
  nom text not null,
  prenom text not null,
  num_paiement text not null,
  date_inscription text not null,
  statut text not null default 'En attente',
  created_at timestamp with time zone not null default now()
);

alter table public.inscriptions enable row level security;

create policy "Allow insert for everyone" on public.inscriptions
for insert with check (true);

create policy "Allow select for everyone" on public.inscriptions
for select using (true);

create policy "Allow update for everyone" on public.inscriptions
for update using (true) with check (true);

create policy "Allow delete for everyone" on public.inscriptions
for delete using (true);

-- Optional: default number generation in admin list
-- Use the id as the registration number in the UI: id padded to 3 digits.
